test_set = [
        ("France is in Africa?", False),
        ("Did George Clooney received Academy Award?", True),
        ("Is Jerusalem the capital of Israel?", True),
        ("Tel Aviv is the capital of Israel?", False),
        ("Benjamin Netanyahu is the president of the USA?", False),
        ("Donald Trump is the president of the USA?", True),
        ("Benjamin Netanyahu is the president of the United States?", True),
        ("Donald Trump is the president of the United States?", True),
        ("Did Microsoft run into bankruptcy?", False),
        ("Did Iceland run into bankruptcy?", True),
        ("Is Zara a swedish company?", False),
        ("Is Zara a spanish company?", True),
        ("Is Barack Obama black?", True),
        ("Did a tsunami hit Israel?", False),
        ("Did a tsunami hit Indonesia?", True),
        ("Is Python a programming language?", True),
        ("Is Donald Trump a women?", False),
        ("Is Killian MBappe dead?", False),
        ("is Donald Trump alive ?", True),
        ("is Kinder a spanish company ?", False),
        ("is Amy Winehouse american ?", False),
        ("is Bob Dylan american ?", True),
        ("is George Clooney an actor?", True),
        ("Is red wine bad for you?", False),
        ("Empire State is in israel?", False),
        ("Empire State is in United States?", True),
        ("is Aretha Franklin dead ?", True),
        ("Freddie Mercury is from Queen?", True),
        ("Freddie Mercury is from Beatles?", False),
        ("does a dog has 3 legs?", False),
        ("car has wheels?", True),
        ("car has no wheels?", False),
        ("Is Oussama Ben Laden dead?", True),
        ("Data Science is a sexy job?", True),
        ("France is a in Africa?", False),
    ]